version: 1.1.x.{build}
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
- SET
- 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
environment:
  matrix:
<% @configs['matrix'].each do |matrix| -%>
  - PUPPET_GEM_VERSION: <%= matrix['PUPPET_GEM_VERSION'] %>
    RUBY_VER: <%= matrix['RUBY_VER'] %>
<% end -%>
<% if @configs['matrix_extras'] -%>
<%   @configs['matrix_extras'].each do |extra| -%>
  - PUPPET_GEM_VERSION: <%= extra['PUPPET_GEM_VERSION'] %>
    RUBY_VER: <%= extra['RUBY_VER'] %>
<%   end -%>
<% end -%>
matrix:
  fast_finish: true
install:
- SET PATH=C:\Ruby%RUBY_VER%\bin;%PATH%
- ps: |
    # AppVeyor appears to have OpenSSL headers available already
    # which msys2 would normally install with:
    # pacman -S mingw-w64-x86_64-openssl --noconfirm
    #
    if ( $(ruby --version) -match "^ruby\s+2\.4" ) {
      Write-Output "Building OpenSSL gem ~> 2.0.4 to fix Ruby 2.4 / AppVeyor issue"
      gem install openssl --version '~> 2.0.4' --no-ri --no-rdoc
    }

    gem list openssl
    ruby -ropenssl -e 'puts \"OpenSSL Version - #{OpenSSL::OPENSSL_VERSION}\"; puts \"OpenSSL Library Version - #{OpenSSL::OPENSSL_LIBRARY_VERSION}\"'
- <%= @configs['appveyor_bundle_install'] %>
- type Gemfile.lock
build: off
test_script:
- bundle exec puppet -V
- ruby -v
<% @configs['test_script'].each do |script| -%>
- <%= script %>
<% end -%>
notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
